### PR TITLE
Update i18n zh-CN(cn.json)

### PR DESCRIPTION
**Pull request by AnotiaWang**
Updated some zh-CN translations, because the former version has some serious errors which may lead to misunderstanding or confusion.

### CODE REVIEW

**Review by KnowsCount — APPROVED** [review]

**Comment by KnowsCount** [comment]
haha I was trying to be funny at some places.. yea it would be a good idea

**Comment by AnotiaWang** [comment]
> haha I was trying to be funny at some places.. yea it would be a good idea

But some of them appear to be mistranslations... They don't even make sense

**Comment by KnowsCount** [comment]
yea I know.「渠道」or 「您已经有这个名字了」for instance... 
Also, would you mind to change the traditional Chinese one too?– Or else I will do that later.

**Comment by AnotiaWang** [comment]
> yea I know.「渠道」or 「您已经有这个名字了」for instance... 
> Also, would you mind to change the traditional Chinese one too?– Or else I will do that later. 

Sorry I don't have much time at this moment. You can do that if you like, thanks 😄

**Comment by marzavec** [comment]
Thanks guys!

**Comment by marzavec** [comment]
Latest changed have been compiled and pushed to beta.hack.chat - you may need to refresh without cache to see the new changes

**Comment by AnotiaWang** [comment]
> Latest changed have been compiled and pushed to beta.hack.chat - you may need to refresh without cache to see the new changes

Thank you😆

**Pull request merged**
